// Mocks generated by Mockito 5.3.0 from annotations
// in ditonton/test/presentation/provider/tv/tv_detail_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ditonton/common/failure.dart' as _i7;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i13;
import 'package:ditonton/domain/entities/tv.dart' as _i10;
import 'package:ditonton/domain/entities/tv_detail.dart' as _i8;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i4;
import 'package:ditonton/domain/repositories/tv_repository.dart' as _i2;
import 'package:ditonton/domain/usecases/get_watchlist_status.dart' as _i11;
import 'package:ditonton/domain/usecases/remove_watchlist.dart' as _i14;
import 'package:ditonton/domain/usecases/save_watchlist.dart' as _i12;
import 'package:ditonton/domain/usecases/tv/get_tv_detail.dart' as _i5;
import 'package:ditonton/domain/usecases/tv/get_tv_recommendations.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvRepository_0 extends _i1.SmartFake implements _i2.TvRepository {
  _FakeTvRepository_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeMovieRepository_2 extends _i1.SmartFake
    implements _i4.MovieRepository {
  _FakeMovieRepository_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [GetTvDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvDetail extends _i1.Mock implements _i5.GetTvDetail {
  MockGetTvDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue:
                  _FakeTvRepository_0(this, Invocation.getter(#repository)))
          as _i2.TvRepository);
  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.TvDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: _i6.Future<_i3.Either<_i7.Failure, _i8.TvDetail>>.value(
              _FakeEither_1<_i7.Failure, _i8.TvDetail>(
                  this, Invocation.method(#execute, [id])))) as _i6
          .Future<_i3.Either<_i7.Failure, _i8.TvDetail>>);
}

/// A class which mocks [GetTvRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvRecommendations extends _i1.Mock
    implements _i9.GetTvRecommendations {
  MockGetTvRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue:
                  _FakeTvRepository_0(this, Invocation.getter(#repository)))
          as _i2.TvRepository);
  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i10.Tv>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: _i6.Future<_i3.Either<_i7.Failure, List<_i10.Tv>>>.value(
              _FakeEither_1<_i7.Failure, List<_i10.Tv>>(
                  this, Invocation.method(#execute, [id])))) as _i6
          .Future<_i3.Either<_i7.Failure, List<_i10.Tv>>>);
}

/// A class which mocks [GetWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatus extends _i1.Mock
    implements _i11.GetWatchListStatus {
  MockGetWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
              returnValue:
                  _FakeMovieRepository_2(this, Invocation.getter(#repository)))
          as _i4.MovieRepository);
  @override
  _i6.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: _i6.Future<bool>.value(false)) as _i6.Future<bool>);
}

/// A class which mocks [SaveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlist extends _i1.Mock implements _i12.SaveWatchlist {
  MockSaveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get movieRepository => (super.noSuchMethod(
          Invocation.getter(#movieRepository),
          returnValue:
              _FakeMovieRepository_2(this, Invocation.getter(#movieRepository)))
      as _i4.MovieRepository);
  @override
  _i2.TvRepository get tvRepository =>
      (super.noSuchMethod(Invocation.getter(#tvRepository),
              returnValue:
                  _FakeTvRepository_0(this, Invocation.getter(#tvRepository)))
          as _i2.TvRepository);
  @override
  _i6.Future<_i3.Either<_i7.Failure, String>> executeMovie(
          _i13.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#executeMovie, [movie]),
              returnValue: _i6.Future<_i3.Either<_i7.Failure, String>>.value(
                  _FakeEither_1<_i7.Failure, String>(
                      this, Invocation.method(#executeMovie, [movie]))))
          as _i6.Future<_i3.Either<_i7.Failure, String>>);
  @override
  _i6.Future<_i3.Either<_i7.Failure, String>> executeTv(_i8.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#executeTv, [tv]),
              returnValue: _i6.Future<_i3.Either<_i7.Failure, String>>.value(
                  _FakeEither_1<_i7.Failure, String>(
                      this, Invocation.method(#executeTv, [tv]))))
          as _i6.Future<_i3.Either<_i7.Failure, String>>);
}

/// A class which mocks [RemoveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlist extends _i1.Mock implements _i14.RemoveWatchlist {
  MockRemoveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MovieRepository get movieRepository => (super.noSuchMethod(
          Invocation.getter(#movieRepository),
          returnValue:
              _FakeMovieRepository_2(this, Invocation.getter(#movieRepository)))
      as _i4.MovieRepository);
  @override
  _i2.TvRepository get tvRepository =>
      (super.noSuchMethod(Invocation.getter(#tvRepository),
              returnValue:
                  _FakeTvRepository_0(this, Invocation.getter(#tvRepository)))
          as _i2.TvRepository);
  @override
  _i6.Future<_i3.Either<_i7.Failure, String>> executeMovie(
          _i13.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#executeMovie, [movie]),
              returnValue: _i6.Future<_i3.Either<_i7.Failure, String>>.value(
                  _FakeEither_1<_i7.Failure, String>(
                      this, Invocation.method(#executeMovie, [movie]))))
          as _i6.Future<_i3.Either<_i7.Failure, String>>);
  @override
  _i6.Future<_i3.Either<_i7.Failure, String>> executeTv(_i8.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#executeTv, [tv]),
              returnValue: _i6.Future<_i3.Either<_i7.Failure, String>>.value(
                  _FakeEither_1<_i7.Failure, String>(
                      this, Invocation.method(#executeTv, [tv]))))
          as _i6.Future<_i3.Either<_i7.Failure, String>>);
}
